wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 30
Loss fn:
  desc: null
  value: NCC, L2_norm
Optimizer:
  desc: null
  value: Adam
NCC Hyperparameters:
  desc: null
  value: 1
L2_norm Hyperparameters:
  desc: null
  value: 0.1
Batch Size:
  desc: null
  value: 4
NCC_Win_Size:
  desc: null
  value: 9
Epochs storage:
  desc: null
  value: /nfs/masi/krishar1/SPIE_2025_InhaleExhaleCT/experiments/voxelmorph_non_harmonized
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721933824
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
